import { useEffect, useMemo, useState } from 'react';
import { ActionIcon, Alert, Badge, Button, Card, Checkbox, Divider, Group, NumberInput, PasswordInput, Progress, ScrollArea, Select, SimpleGrid, Slider, Stack, Switch, Table, Tabs, TagsInput, Text, TextInput, Title, Tooltip } from '@mantine/core';
import { IconActivity, IconAdjustments, IconBolt, IconBrain, IconCheck, IconKey, IconPlugConnected, IconRefresh, IconRobot, IconRoute, IconSettings, IconShield, IconUsers } from '@tabler/icons-react';
import { api, json } from '../api';

type Settings = Record<string, Record<string, any>>;
interface AdminUser {id:string;username:string;displayName:string;email:string;role:string;teamName:string;active:boolean;createdAt:string}
interface Audit {id:number;action:string;resourceType:string;resourceId:string;actor:string;createdAt:string}

const menu = [
  ['overview','운영 현황',IconActivity],['general','일반',IconSettings],['oidc','Keycloak SSO',IconPlugConnected],['dream','Dream Layer',IconBrain],['ai_gateway','AI Gateway',IconRobot],['security','키 · 권한',IconShield],['workflow','검토 프로세스',IconRoute],['users','사용자',IconUsers],['audit','감사 로그',IconAdjustments],
] as const;

export default function AdminPage(){
  const [section,setSection]=useState<(typeof menu)[number][0]>('overview');const [settings,setSettings]=useState<Settings>({});const [metrics,setMetrics]=useState<Record<string,any>>({});const [users,setUsers]=useState<AdminUser[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const load=()=>Promise.all([api<Settings>('/admin/settings').then(setSettings),api<Record<string,any>>('/admin/metrics').then(setMetrics),api<{users:AdminUser[]}>('/admin/users').then(v=>setUsers(v.users)),api<{audit:Audit[]}>('/admin/audit').then(v=>setAudit(v.audit))]);
  useEffect(()=>{void load()},[]);
  const update=(name:string,key:string,value:any)=>setSettings(all=>({...all,[name]:{...all[name],[key]:value}}));
  const save=async(name:string)=>{setError('');try{await api(`/admin/settings/${name}`,json('PUT',settings[name]));setMessage(`${menu.find(v=>v[0]===name)?.[1]||name} 설정을 저장했습니다.`);await load()}catch(e){setError(e instanceof Error?e.message:'설정을 저장하지 못했습니다.')}};
  const testOIDC=async()=>{try{const v=await api<{message:string}>('/admin/oidc/test',{method:'POST'});setMessage(v.message)}catch(e){setError(e instanceof Error?e.message:'연결 실패')}};
  const updateUser=async(user:AdminUser,patch:Partial<AdminUser>)=>{const next={...user,...patch};await api(`/admin/users/${user.id}`,json('PUT',{role:next.role,active:next.active,teamName:next.teamName||''}));setUsers(all=>all.map(v=>v.id===user.id?next:v));};
  return <main className="admin-layout"><aside className="admin-menu nav-scroll"><Stack h="100%"><Group px="sm" pt={60}><div className="brand-mark">um</div><div><Text fw={700}>Service Admin</Text><Text size="xs" c="gray.5">umm control room</Text></div></Group><Divider color="dark.4" my="sm"/><ScrollArea className="nav-scroll" type="auto"><Stack gap={4}>{menu.map(([key,label,Icon])=><Button key={key} fullWidth justify="flex-start" variant={section===key?'light':'subtle'} color={section===key?'grape':'gray'} leftSection={<Icon size={18}/>} onClick={()=>setSection(key)}>{label}</Button>)}</Stack></ScrollArea><Text size="xs" c="gray.6" mt="auto" px="sm">모든 변경은 감사 로그에 기록됩니다.</Text></Stack></aside><section className="admin-content nav-scroll"><Stack maw={1100} mx="auto" gap="xl"><Group justify="space-between"><div><Text size="xs" c="grape.7" fw={750}>SERVICE ADMINISTRATION</Text><Title order={1} mt={4}>{menu.find(v=>v[0]===section)?.[1]}</Title></div><Tooltip label="새로고침"><ActionIcon size="lg" variant="light" onClick={()=>void load()}><IconRefresh size={19}/></ActionIcon></Tooltip></Group>{message&&<Alert color="green" icon={<IconCheck size={18}/>} withCloseButton onClose={()=>setMessage('')}>{message}</Alert>}{error&&<Alert color="red" withCloseButton onClose={()=>setError('')}>{error}</Alert>}
    {section==='overview'&&<Overview metrics={metrics} onRun={async()=>{await api('/admin/dreams/run',{method:'POST'});setMessage('Dream 작업을 큐에 등록했습니다.')}}/>}
    {section==='general'&&settings.general&&<SettingCard title="서비스 기본 정보" description="재시작 없이 적용되며 로그인 화면과 서비스 전반에 반영됩니다." onSave={()=>save('general')}><TextInput label="서비스 이름" value={settings.general.service_name||''} onChange={e=>update('general','service_name',e.currentTarget.value)}/><TextInput label="공개 URL" description="OIDC Callback과 Origin 검증에 사용합니다." value={settings.general.public_url||''} onChange={e=>update('general','public_url',e.currentTarget.value)}/><SimpleGrid cols={{base:1,sm:2}}><NumberInput label="세션 유지 시간" suffix=" 시간" min={1} max={720} value={settings.general.session_hours||24} onChange={v=>update('general','session_hours',v)}/><TextInput label="서비스 시간대" placeholder="Asia/Seoul" value={settings.general.timezone||''} onChange={e=>update('general','timezone',e.currentTarget.value)}/></SimpleGrid></SettingCard>}
    {section==='oidc'&&settings.oidc&&<SettingCard title="Keycloak SSO · OIDC" description="Issuer URL, Client ID, Client Secret만으로 Discovery를 통해 자동 연결합니다." onSave={()=>save('oidc')} actions={<Button variant="light" leftSection={<IconBolt size={16}/>} onClick={()=>void testOIDC()}>연결 시험</Button>}><Switch size="lg" label="Keycloak SSO 활성화" checked={!!settings.oidc.enabled} onChange={e=>update('oidc','enabled',e.currentTarget.checked)}/><TextInput label="Issuer URL" placeholder="https://keycloak.internal/realms/umm" value={settings.oidc.issuer_url||''} onChange={e=>update('oidc','issuer_url',e.currentTarget.value)}/><SimpleGrid cols={{base:1,sm:2}}><TextInput label="Client ID" value={settings.oidc.client_id||''} onChange={e=>update('oidc','client_id',e.currentTarget.value)}/><PasswordInput label="Client Secret" value={settings.oidc.client_secret||''} onChange={e=>update('oidc','client_secret',e.currentTarget.value)}/><TextInput label="관리자 그룹/역할" value={settings.oidc.admin_group||''} onChange={e=>update('oidc','admin_group',e.currentTarget.value)}/><TextInput label="팀장 그룹/역할" value={settings.oidc.team_lead_group||''} onChange={e=>update('oidc','team_lead_group',e.currentTarget.value)}/></SimpleGrid><Alert color="blue">Keycloak Confidential Client에서 Standard Flow를 켜고 Callback을 <b>{settings.general?.public_url}/api/v1/auth/oidc/callback</b>으로 정확히 등록하세요.</Alert></SettingCard>}
    {section==='dream'&&settings.dream&&<DreamSettings value={settings.dream} update={(k,v)=>update('dream',k,v)} save={()=>save('dream')}/>} 
    {section==='ai_gateway'&&settings.ai_gateway&&<SettingCard title="내부 AI Gateway" description="OpenAI 호환 Chat Completions 엔드포인트를 사용합니다. 외부 연결 없이 내부 모델 서버를 지정할 수 있습니다." onSave={()=>save('ai_gateway')}><TextInput label="Base URL" placeholder="http://llm-gateway.internal:8000" value={settings.ai_gateway.base_url||''} onChange={e=>update('ai_gateway','base_url',e.currentTarget.value)}/><PasswordInput label="API Key" value={settings.ai_gateway.api_key||''} onChange={e=>update('ai_gateway','api_key',e.currentTarget.value)}/><SimpleGrid cols={{base:1,sm:2}}><NumberInput label="Timeout" suffix=" 초" min={5} max={300} value={settings.ai_gateway.timeout_seconds} onChange={v=>update('ai_gateway','timeout_seconds',v)}/><NumberInput label="재시도" min={0} max={5} value={settings.ai_gateway.max_retries} onChange={v=>update('ai_gateway','max_retries',v)}/><NumberInput label="입력 $ / 1M token" min={0} decimalScale={4} value={settings.ai_gateway.input_cost_per_million} onChange={v=>update('ai_gateway','input_cost_per_million',v)}/><NumberInput label="출력 $ / 1M token" min={0} decimalScale={4} value={settings.ai_gateway.output_cost_per_million} onChange={v=>update('ai_gateway','output_cost_per_million',v)}/></SimpleGrid><TextInput label="Prompt Version" value={settings.ai_gateway.prompt_version||''} onChange={e=>update('ai_gateway','prompt_version',e.currentTarget.value)}/><Switch label="원문 Prompt 로그 저장" description="개인정보 최소화를 위해 기본 OFF를 권장합니다. 현재 구현은 OFF일 때 원문을 저장하지 않습니다." checked={!!settings.ai_gateway.log_prompt} onChange={e=>update('ai_gateway','log_prompt',e.currentTarget.checked)}/></SettingCard>}
    {section==='security'&&settings.security&&<SettingCard title="개인 키 권한 체계" description="사용자가 자신의 키에 부여할 수 있는 권한과 회전 정책입니다." onSave={()=>save('security')}><TagsInput label="허용 API/MCP Scopes" value={settings.security.api_key_scopes||[]} onChange={v=>update('security','api_key_scopes',v)} splitChars={[',',' ']}/><SimpleGrid cols={{base:1,sm:2}}><NumberInput label="기본 키 만료" suffix=" 일" min={1} max={3650} value={settings.security.default_key_days} onChange={v=>update('security','default_key_days',v)}/><NumberInput label="회전 중첩 시간" suffix=" 시간" min={0} max={168} value={settings.security.rotation_overlap_hours} onChange={v=>update('security','rotation_overlap_hours',v)}/></SimpleGrid></SettingCard>}
    {section==='workflow'&&settings.workflow&&<SettingCard title="팀장 검토 · 승인" description="활성화한 작업에만 승인/반려 단계를 삽입합니다. OFF이면 프로세스 자체가 제외됩니다." onSave={()=>save('workflow')}><Switch size="lg" label="검토 프로세스 활성화" checked={!!settings.workflow.enabled} onChange={e=>update('workflow','enabled',e.currentTarget.checked)}/><Checkbox.Group label="승인이 필요한 작업" value={settings.workflow.actions||[]} onChange={v=>update('workflow','actions',v)}><Stack mt="sm"><Checkbox value="space_share" label="팀 공간 공유"/><Checkbox value="export" label="외부 내보내기"/><Checkbox value="dream_publish" label="Dream 공개"/></Stack></Checkbox.Group></SettingCard>}
    {section==='users'&&<Users users={users} update={updateUser}/>} {section==='audit'&&<AuditTable entries={audit}/>} 
  </Stack></section></main>;
}

function SettingCard({title,description,children,onSave,actions}:{title:string;description:string;children:React.ReactNode;onSave:()=>void;actions?:React.ReactNode}){return <Card radius="lg" p={{base:'lg',sm:'xl'}} withBorder><Group justify="space-between" align="flex-start"><div><Title order={2} fz="xl">{title}</Title><Text c="dimmed" mt={5}>{description}</Text></div>{actions}</Group><Divider my="xl"/><Stack gap="lg">{children}<Group justify="flex-end"><Button onClick={onSave}>저장</Button></Group></Stack></Card>}

function DreamSettings({value,update,save}:{value:Record<string,any>;update:(k:string,v:any)=>void;save:()=>void}){return <SettingCard title="Dream Settings" description="좋은 Dream이 없으면 생성하지 않는 것을 기본 원칙으로 합니다." onSave={save}><SimpleGrid cols={{base:1,sm:2}}><Switch size="lg" label="Dream 기능" checked={!!value.enabled} onChange={e=>update('enabled',e.currentTarget.checked)}/><Switch size="lg" label="자동 생성" checked={!!value.automatic} onChange={e=>update('automatic',e.currentTarget.checked)}/><TextInput label="생성 시간" type="time" value={value.schedule||'02:00'} onChange={e=>update('schedule',e.currentTarget.value)}/><Select label="생성 주기" value={value.frequency} data={[{value:'daily',label:'매일'},{value:'weekdays',label:'평일'},{value:'weekends',label:'주말'}]} onChange={v=>v&&update('frequency',v)}/><NumberInput label="사용자당 Dream" suffix=" 장" min={1} max={3} value={value.count} onChange={v=>update('count',v)}/><NumberInput label="최소 메모" suffix=" 개" min={2} max={100} value={value.min_notes} onChange={v=>update('min_notes',v)}/><NumberInput label="최근 분석 범위" suffix=" 일" min={1} max={365} value={value.context_days} onChange={v=>update('context_days',v)}/><NumberInput label="최대 Context 메모" suffix=" 개" min={2} max={100} value={value.max_context_notes} onChange={v=>update('max_context_notes',v)}/><TextInput label="Model" value={value.model||''} onChange={e=>update('model',e.currentTarget.value)}/><NumberInput label="Token Limit" min={64} max={4096} value={value.token_limit} onChange={v=>update('token_limit',v)}/><NumberInput label="월 사용자 호출 제한" min={1} max={1000} value={value.monthly_limit} onChange={v=>update('monthly_limit',v)}/><Switch label="사용자 개별 OFF 허용" checked={!!value.allow_user_disable} onChange={e=>update('allow_user_disable',e.currentTarget.checked)}/></SimpleGrid><div><Group justify="space-between"><Text fw={550}>Creativity</Text><Text>{Number(value.temperature).toFixed(1)}</Text></Group><Slider min={0} max={1.5} step={.1} value={value.temperature} onChange={v=>update('temperature',v)} mt="sm"/></div><div><Group justify="space-between"><Text fw={550}>Dream 노출 최소 Score</Text><Text>{Math.round(value.quality_threshold*100)}%</Text></Group><Slider min={0} max={1} step={.05} color="grape" value={value.quality_threshold} onChange={v=>update('quality_threshold',v)} mt="sm"/></div><Switch label="Quiet Mode" description="가치가 높은 경우에만 생성" checked={!!value.quiet_mode} onChange={e=>update('quiet_mode',e.currentTarget.checked)}/></SettingCard>}

function Overview({metrics,onRun}:{metrics:Record<string,any>;onRun:()=>void}){const d=metrics.dream||{};const cards=[['전체 사용자',metrics.users,IconUsers],['활성 사용자',metrics.activeUsers,IconActivity],['생각',metrics.notes,IconBrain],['공간',metrics.spaces,IconAdjustments],['Dream 생성',d.generated||0,IconMoon],['AI 호출',d.apiCalls||0,IconBolt]];return <Stack><SimpleGrid cols={{base:2,md:3}}>{cards.map(([label,value,Icon]:any)=><Card key={label} radius="lg" withBorder><Group justify="space-between"><Text c="dimmed" size="sm">{label}</Text><Icon size={18} color="#8066a5"/></Group><Text fz={30} fw={720} mt="sm">{Number(value||0).toLocaleString()}</Text></Card>)}</SimpleGrid><Card radius="lg" p="xl" withBorder><Group justify="space-between"><div><Title order={2} fz="xl">Dream 운영</Title><Text c="dimmed">이번 달 품질과 사용량</Text></div><Button leftSection={<IconBolt size={16}/>} onClick={onRun}>지금 큐 생성</Button></Group><SimpleGrid cols={{base:1,sm:3}} mt="xl"><Metric label="평균 품질" value={`${Math.round((d.avgQualityScore||0)*100)}%`} progress={(d.avgQualityScore||0)*100}/><Metric label="입력 Token" value={Number(d.inputTokens||0).toLocaleString()}/><Metric label="예상 비용" value={`$${((d.costMicros||0)/1_000_000).toFixed(2)}`}/></SimpleGrid></Card></Stack>}
const IconMoon=IconBrain;
function Metric({label,value,progress}:{label:string;value:string;progress?:number}){return <div><Text size="sm" c="dimmed">{label}</Text><Text fz="xl" fw={680} mt={4}>{value}</Text>{progress!==undefined&&<Progress value={progress} color="grape" mt="sm"/>}</div>}

function Users({users,update}:{users:AdminUser[];update:(u:AdminUser,p:Partial<AdminUser>)=>Promise<void>}){return <Card radius="lg" withBorder p="xl"><Text c="dimmed" mb="lg">Keycloak 그룹 매핑 또는 여기에서 역할과 팀을 변경할 수 있습니다.</Text><Table.ScrollContainer minWidth={780}><Table verticalSpacing="md" highlightOnHover><Table.Thead><Table.Tr><Table.Th>사용자</Table.Th><Table.Th>역할</Table.Th><Table.Th>팀</Table.Th><Table.Th>상태</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{users.map(u=><Table.Tr key={u.id}><Table.Td><Text fw={600}>{u.displayName}</Text><Text size="xs" c="dimmed">{u.username} · {u.email}</Text></Table.Td><Table.Td><Select w={140} value={u.role} data={[{value:'user',label:'사용자'},{value:'team_lead',label:'팀장'},{value:'admin',label:'관리자'}]} onChange={v=>v&&void update(u,{role:v})}/></Table.Td><Table.Td><TextInput w={160} defaultValue={u.teamName} placeholder="팀 없음" onBlur={e=>void update(u,{teamName:e.currentTarget.value})}/></Table.Td><Table.Td><Switch checked={u.active} onChange={e=>void update(u,{active:e.currentTarget.checked})}/></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer></Card>}
function AuditTable({entries}:{entries:Audit[]}){return <Card radius="lg" withBorder p="xl"><Table.ScrollContainer minWidth={760}><Table verticalSpacing="sm" striped><Table.Thead><Table.Tr><Table.Th>시각</Table.Th><Table.Th>행위자</Table.Th><Table.Th>작업</Table.Th><Table.Th>대상</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{entries.map(e=><Table.Tr key={e.id}><Table.Td><Text size="sm">{new Date(e.createdAt).toLocaleString('ko-KR')}</Text></Table.Td><Table.Td>{e.actor}</Table.Td><Table.Td><Badge variant="light" color="gray">{e.action}</Badge></Table.Td><Table.Td>{e.resourceType} · <Text span c="dimmed" size="xs">{e.resourceId}</Text></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer></Card>}
