import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from 'react';
import { ActionIcon, Alert, Badge, Button, Divider, Group, Loader, Menu, Modal, Paper, ScrollArea, Select, Stack, Text, TextInput, Tooltip } from '@mantine/core';
import { IconArrowRight, IconBrain, IconCheck, IconChevronDown, IconDots, IconDownload, IconEdit, IconFileTypePdf, IconFocusCentered, IconLayoutGrid, IconMarkdown, IconMoonStars, IconPhoto, IconPlus, IconSearch, IconSettings, IconShare, IconSparkles, IconTrash, IconX } from '@tabler/icons-react';
import { ReactFlow, addEdge, Background, BackgroundVariant, Controls, MiniMap, ReactFlowProvider, useEdgesState, useNodesState, useReactFlow, type Connection, type Edge, type Node, type OnNodeDrag } from '@xyflow/react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, json, type Space, type ThoughtEdge, type ThoughtNote } from '../api';
import PostItNode, { type PostItData } from '../components/PostItNode';
import { useAuth } from '../auth-context';
import { toPng } from 'html-to-image';

const nodeTypes = { postit: PostItNode };
const palette: Record<string, string> = { yellow: '#fff0a8', blue: '#dbeeff', purple: '#e9def8', lavender: '#e8e2f1', green: '#d9f0dc', red: '#f8deda', gray: '#e9e7e1' };
const aiTools = [['summarize','요약'],['questions','질문 만들기'],['expand','확장'],['challenge','반대 관점'],['actions','실행 항목']];
const normalizeSearch = (value: string) => value.normalize('NFKC').toLocaleLowerCase('ko-KR').trim();

interface DreamHistory { dreamId: string; status: string; content: string; spaceId: string; qualityScore: number; }
interface HistoryAction { id: string; before: { x: number; y: number }; after: { x: number; y: number }; }
interface RelatedThought {note:ThoughtNote;score:number;reason:string}
interface Cluster {id:string;label:string;noteIds:string[];cohesion:number}
interface SpaceMember {id:string;username:string;displayName:string;email:string;permission:string}
type NoteWritePayload = Pick<ThoughtNote, 'content'|'title'|'color'|'kind'|'x'|'y'|'width'|'height'|'rotation'|'version'>;

const noteWritePayload = (note: ThoughtNote): NoteWritePayload => ({
  content: note.content, title: note.title, color: note.color, kind: note.kind,
  x: note.x, y: note.y, width: note.width, height: note.height,
  rotation: note.rotation, version: note.version,
});

function CanvasInner() {
  const params = useParams(); const navigate = useNavigate(); const flow = useReactFlow();
  const {user}=useAuth();
  const [spaces, setSpaces] = useState<Space[]>([]); const [activeSpace, setActiveSpace] = useState('');
  const [notes, setNotes] = useState<ThoughtNote[]>([]); const [rawEdges, setRawEdges] = useState<ThoughtEdge[]>([]);
  const [nodes, setNodes, onNodesChange] = useNodesState<Node<PostItData>>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);
  const [query, setQuery] = useState(''); const [capture, setCapture] = useState(''); const [loading, setLoading] = useState(true);
  const [searchIndex,setSearchIndex]=useState(-1);const [spaceQuery,setSpaceQuery]=useState('');const [spaceManagerOpen,setSpaceManagerOpen]=useState(false);const [newSpaceName,setNewSpaceName]=useState('');const [spaceDrafts,setSpaceDrafts]=useState<Record<string,string>>({});const [spaceBusy,setSpaceBusy]=useState('');const [spaceError,setSpaceError]=useState('');const [deleteCandidate,setDeleteCandidate]=useState<Space>();const [deleteConfirmation,setDeleteConfirmation]=useState('');
  const [morningDream, setMorningDream] = useState<DreamHistory>();
  const [related,setRelated]=useState<{source:string;items:RelatedThought[]}>();const [aiResult,setAIResult]=useState<{mode:string;content:string}>();const [aiBusy,setAIBusy]=useState(false);
  const [shareOpen,setShareOpen]=useState(false);const [members,setMembers]=useState<SpaceMember[]>([]);const [canManage,setCanManage]=useState(false);const [shareUser,setShareUser]=useState('');const [sharePermission,setSharePermission]=useState('edit');const [shareMessage,setShareMessage]=useState('');
  const notesRef = useRef<Record<string, ThoughtNote>>({}); const queues = useRef<Record<string, Promise<void>>>({});
  const dragStart = useRef<Record<string, {x:number;y:number}>>({}); const undo = useRef<HistoryAction[]>([]); const redo = useRef<HistoryAction[]>([]);

  const syncNotes = (next: ThoughtNote[]) => { setNotes(next); notesRef.current = Object.fromEntries(next.map((n) => [n.id, n])); };
  useEffect(() => { api<{spaces: Space[]}>('/spaces').then(({spaces}) => { setSpaces(spaces);setSpaceDrafts(Object.fromEntries(spaces.map(space=>[space.id,space.name]))); const desired = params.spaceId && spaces.some(s => s.id === params.spaceId) ? params.spaceId : spaces[0]?.id; if (desired) { setActiveSpace(desired); if (!params.spaceId) navigate(`/space/${desired}`, { replace: true }); } }).catch(console.error); }, []);
  useEffect(() => { if (params.spaceId && params.spaceId !== activeSpace) setActiveSpace(params.spaceId); }, [params.spaceId]);
  const loadCanvas=useCallback(async(silent=false)=>{if(!activeSpace)return;if(!silent)setLoading(true);try{const v=await api<{notes:ThoughtNote[];edges:ThoughtEdge[]}>(`/spaces/${activeSpace}/notes`);syncNotes(v.notes);setRawEdges(v.edges)}finally{if(!silent)setLoading(false)}},[activeSpace]);
  useEffect(() => { if (!activeSpace) return; void loadCanvas(); api<{dreams: DreamHistory[]}>('/dreams').then(({dreams}) => { const fresh = dreams.find(d => d.spaceId === activeSpace && d.status === 'created'); if (fresh && !sessionStorage.getItem(`dream:${fresh.dreamId}`)) setMorningDream(fresh); }).catch(() => undefined); }, [activeSpace,loadCanvas]);
  useEffect(()=>{if(!activeSpace)return;const stream=new EventSource(`/api/v1/spaces/${activeSpace}/events`);stream.addEventListener('space-change',(event)=>{try{const data=JSON.parse((event as MessageEvent).data);if(data.actorId!==user?.id)void loadCanvas(true)}catch{void loadCanvas(true)}});return()=>stream.close()},[activeSpace,user?.id,loadCanvas]);

  const persist = useCallback((id: string, patch: Partial<ThoughtNote>) => {
    const current = notesRef.current[id]; if (!current) return;
    notesRef.current[id] = { ...current, ...patch }; setNotes((all) => all.map((n) => n.id === id ? { ...n, ...patch } : n));
    const previous = queues.current[id] || Promise.resolve();
    queues.current[id] = previous.catch(() => undefined).then(async () => {
      const base = notesRef.current[id]; if (!base) return;
      const updated = await api<ThoughtNote>(`/notes/${id}`, json('PUT', noteWritePayload(base)));
      notesRef.current[id] = { ...notesRef.current[id], version: updated.version, updatedAt: updated.updatedAt };
      setNotes((all) => all.map((n) => n.id === id ? { ...n, version: updated.version, updatedAt: updated.updatedAt } : n));
    }).catch((error) => console.error('autosave failed', error));
  }, []);

  const remove = useCallback(async (id: string) => { await api(`/notes/${id}`, { method: 'DELETE' }); delete notesRef.current[id]; setNotes((all) => all.filter((n) => n.id !== id)); setRawEdges((all) => all.filter((e) => e.source !== id && e.target !== id)); }, []);
  const restore=useCallback(async(id:string)=>{const result=await api<{history:Array<{version:number;createdAt:string}>}>(`/notes/${id}/history`);const latest=result.history[0];if(!latest){window.alert('복원할 이전 버전이 없습니다.');return};if(!window.confirm(`${new Date(latest.createdAt).toLocaleString('ko-KR')}의 버전으로 되돌릴까요? 현재 상태도 기록에 남습니다.`))return;const restored=await api<ThoughtNote>(`/notes/${id}/restore/${latest.version}`,{method:'POST'});notesRef.current[id]=restored;setNotes(all=>all.map(n=>n.id===id?restored:n))},[]);

  const gravity = useCallback((selectedID?:string) => { const selected = selectedID ? flow.getNode(selectedID) : flow.getNodes().find(n => n.selected); if (!selected) return; const related = new Set<string>(); rawEdges.forEach(e => { if (e.source === selected.id) related.add(e.target); if (e.target === selected.id) related.add(e.source); }); [...related].forEach((id, index) => { const angle = index / Math.max(1, related.size) * Math.PI * 2; const patch = { x: selected.position.x + Math.cos(angle) * 330, y: selected.position.y + Math.sin(angle) * 230 }; persist(id, patch); }); },[flow,rawEdges,persist]);
  const discoverRelated=useCallback(async(id:string)=>{const result=await api<{related:RelatedThought[]}>(`/notes/${id}/related?limit=8`);setRelated({source:id,items:result.related});const source=flow.getNode(id);if(source){result.related.forEach((item,index)=>{const angle=index/Math.max(1,result.related.length)*Math.PI*2;persist(item.note.id,{x:source.position.x+Math.cos(angle)*360,y:source.position.y+Math.sin(angle)*245})})}},[flow,persist]);

  const searchTerms=useMemo(()=>normalizeSearch(query).split(/\s+/).filter(Boolean),[query]);
  const searchMatches=useMemo(()=>searchTerms.length===0?notes:notes.filter(note=>{const searchable=normalizeSearch(`${note.title} ${note.content}`);return searchTerms.every(term=>searchable.includes(term))}),[notes,searchTerms]);
  const visibleSpaces=useMemo(()=>{const term=normalizeSearch(spaceQuery);return [...spaces].filter(space=>!term||normalizeSearch(space.name).includes(term)).sort((a,b)=>a.name.localeCompare(b.name,'ko'))},[spaces,spaceQuery]);
  useEffect(() => {
    setNodes(searchMatches.map((note) => ({ id: note.id, type: 'postit', position: { x: note.x, y: note.y }, style: { width: note.width, height: note.height }, data: { note, dimmed: false, relatedCount: note.relatedCount, onGather: discoverRelated, onPatch: persist, onDelete: remove,onRestore:restore } })));
  }, [searchMatches, persist, remove, restore,discoverRelated]);
  useEffect(() => {const visible=new Set(searchMatches.map(note=>note.id));setEdges(rawEdges.filter(edge=>visible.has(edge.source)&&visible.has(edge.target)).map((e) => ({ id: e.id, source: e.source, target: e.target, type: 'smoothstep', animated: e.relation === 'dreamed', label: e.relation === 'related' ? undefined : e.relation })))}, [rawEdges,searchMatches]);

  const createAt = useCallback(async (content: string, x: number, y: number) => {
    if (!activeSpace) return; const trimmed = content.trim();
    const created = await api<ThoughtNote>(`/spaces/${activeSpace}/notes`, json('POST', { content: trimmed, title: '', color: 'yellow', kind: 'thought', x, y, width: 240, height: 160, rotation: Math.round((Math.random() - .5) * 2) }));
    syncNotes([...Object.values(notesRef.current), created]); setCapture('');
  }, [activeSpace]);

  const onPaneDoubleClick = useCallback((event: React.MouseEvent) => { const point = flow.screenToFlowPosition({ x: event.clientX, y: event.clientY }); void createAt('', point.x, point.y); }, [flow, createAt]);
  const connect = useCallback(async (connection: Connection) => { if (!connection.source || !connection.target) return; const created = await api<ThoughtEdge>(`/spaces/${activeSpace}/edges`, json('POST', { source: connection.source, target: connection.target, relation: 'related' })); setRawEdges((all) => [...all, created]); setEdges((all) => addEdge({ ...connection, id: created.id, type: 'smoothstep' }, all)); }, [activeSpace]);
  const onDragStart: OnNodeDrag<Node<PostItData>> = (_, node) => { dragStart.current[node.id] = { ...node.position }; };
  const onDragStop: OnNodeDrag<Node<PostItData>> = (_, node) => { const before = dragStart.current[node.id]; const after = { ...node.position }; if (before && (before.x !== after.x || before.y !== after.y)) { undo.current.push({ id: node.id, before, after }); redo.current = []; } persist(node.id, { x: after.x, y: after.y }); };

  const focusSearchResult=useCallback((step=1)=>{if(searchMatches.length===0)return;const next=(searchIndex+step+searchMatches.length)%searchMatches.length;setSearchIndex(next);const id=searchMatches[next].id;setNodes(all=>all.map(node=>({...node,selected:node.id===id})));window.requestAnimationFrame(()=>void flow.fitView({nodes:[{id}],duration:350,padding:1.4,maxZoom:1.25}))},[flow,searchIndex,searchMatches,setNodes]);

  useEffect(() => {
    const onKey = (event: globalThis.KeyboardEvent) => {
      const target = event.target as HTMLElement; const editing = ['INPUT','TEXTAREA','SELECT'].includes(target.tagName) || target.isContentEditable;
      if (document.querySelector('[role="dialog"]')) return;
      const mod=event.ctrlKey||event.metaKey;const key=event.key.toLocaleLowerCase();
      if (!editing && mod && key==='f') {event.preventDefault();document.getElementById('thought-search')?.focus();return}
      if (!editing && !mod && !event.altKey && key==='n') {event.preventDefault();document.getElementById('quick-thought')?.focus();return}
      if (!editing && !mod && !event.altKey && event.key==='/') {event.preventDefault();document.getElementById('thought-search')?.focus();return}
      if (!editing && (event.key==='Delete'||event.key==='Backspace')) {const selected=flow.getNodes().filter(node=>node.selected).map(node=>node.id);if(selected.length===0)return;event.preventDefault();if(window.confirm(`선택한 생각 ${selected.length}개를 삭제할까요?`))void Promise.all(selected.map(remove));return}
      if (!editing && mod && key==='a') {event.preventDefault();setNodes(all=>all.map(node=>({...node,selected:true})));return}
      if (!editing && !mod && !event.altKey && key==='f') {event.preventDefault();void flow.fitView({duration:400,padding:.25});return}
      if (!editing && event.key==='Escape') {setQuery('');setSearchIndex(-1);setRelated(undefined);setNodes(all=>all.map(node=>({...node,selected:false})));return}
      if (!editing && mod && key==='z') { event.preventDefault(); const action = event.shiftKey ? redo.current.pop() : undo.current.pop(); if (!action) return; const position = event.shiftKey ? action.after : action.before; persist(action.id, position); setNodes((all) => all.map(n => n.id === action.id ? { ...n, position } : n)); (event.shiftKey ? undo.current : redo.current).push(action); }
    }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  }, [flow,persist,remove,setNodes]);

  const captureKey = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === 'Enter' && capture.trim()) { const center = flow.screenToFlowPosition({ x: window.innerWidth / 2, y: window.innerHeight / 2 }); void createAt(capture, center.x - 120, center.y - 80); } };
  const openSpace=(id:string)=>{setQuery('');setSpaceQuery('');navigate(`/space/${id}`)};
  const addSpace=async()=>{const name=newSpaceName.trim();if(!name)return;setSpaceError('');setSpaceBusy('new');try{const created=await api<Space>('/spaces',json('POST',{name}));setSpaces(all=>[...all,created]);setSpaceDrafts(all=>({...all,[created.id]:created.name}));setNewSpaceName('');setSpaceManagerOpen(false);openSpace(created.id)}catch(error){setSpaceError(error instanceof Error?error.message:'공간을 만들지 못했습니다.')}finally{setSpaceBusy('')}};
  const renameSpace=async(space:Space)=>{const name=(spaceDrafts[space.id]||'').trim();if(!name||name===space.name)return;setSpaceError('');setSpaceBusy(space.id);try{const updated=await api<Space>(`/spaces/${space.id}`,json('PUT',{name}));setSpaces(all=>all.map(item=>item.id===space.id?updated:item));setSpaceDrafts(all=>({...all,[space.id]:updated.name}))}catch(error){setSpaceError(error instanceof Error?error.message:'공간 이름을 저장하지 못했습니다.')}finally{setSpaceBusy('')}};
  const deleteSpace=async()=>{if(!deleteCandidate||deleteConfirmation!==deleteCandidate.name)return;setSpaceError('');setSpaceBusy(`delete:${deleteCandidate.id}`);try{await api(`/spaces/${deleteCandidate.id}`,{method:'DELETE'});const result=await api<{spaces:Space[]}>('/spaces');setSpaces(result.spaces);setSpaceDrafts(Object.fromEntries(result.spaces.map(space=>[space.id,space.name])));const next=result.spaces.find(space=>space.id!==deleteCandidate.id)||result.spaces[0];setDeleteCandidate(undefined);setDeleteConfirmation('');if(next&&activeSpace===deleteCandidate.id)openSpace(next.id)}catch(error){setSpaceError(error instanceof Error?error.message:'공간을 삭제하지 못했습니다.')}finally{setSpaceBusy('')}};
  const clusterThoughts=async()=>{const {clusters}=await api<{clusters:Cluster[]}>(`/spaces/${activeSpace}/clusters`);clusters.forEach((cluster,clusterIndex)=>cluster.noteIds.forEach((id,noteIndex)=>persist(id,{x:clusterIndex*620+(noteIndex%2)*270,y:Math.floor(noteIndex/2)*205})));if(clusters.length===0)window.alert('아직 뚜렷한 생각 군집이 없습니다. 조금 더 생각을 붙여보세요.')};
  const assist=async(mode:string)=>{const selected=flow.getNodes().filter(n=>n.selected).map(n=>n.id);if(selected.length===0){window.alert('AI와 발전시킬 생각을 하나 이상 선택하세요.');return};setAIBusy(true);try{setAIResult(await api('/ai/assist',json('POST',{noteIds:selected,mode})))}finally{setAIBusy(false)}};
  const loadMembers=async()=>{const v=await api<{members:SpaceMember[];canManage:boolean}>(`/spaces/${activeSpace}/members`);setMembers(v.members);setCanManage(v.canManage)};const openShare=async()=>{await loadMembers();setShareOpen(true)};const share=async()=>{const v=await api<{required:boolean;status:string}>(`/spaces/${activeSpace}/members`,json('POST',{username:shareUser,permission:sharePermission}));setShareMessage(v.required?'팀장 검토를 요청했습니다. 승인되면 자동으로 공유됩니다.':'공간을 공유했습니다.');setShareUser('');await loadMembers()};const removeMember=async(id:string)=>{await api(`/spaces/${activeSpace}/members/${id}`,{method:'DELETE'});await loadMembers()};
  const ensureExport=async(format:string)=>{const response=await fetch(`/api/v1/spaces/${activeSpace}/export/authorize?format=${format}`,{credentials:'same-origin'});if(response.ok)return true;const payload=await response.json().catch(()=>({}));if(response.status===409&&payload.code==='approval_required'){const request=await api<{required:boolean;status:string}>('/approvals',json('POST',{resourceType:'space',resourceId:activeSpace,action:'export',comment:`${format} 내보내기 요청`}));window.alert(request.required?'팀장 검토를 요청했습니다. 승인 후 24시간 동안 내보낼 수 있습니다.':'내보내기가 허용되었습니다.');return !request.required}throw new Error(payload.error||'내보내기 권한을 확인하지 못했습니다.')};
  const downloadMarkdown=async()=>{if(!await ensureExport('markdown'))return;const response=await fetch(`/api/v1/spaces/${activeSpace}/export/markdown`,{credentials:'same-origin'});if(!response.ok)throw new Error('Markdown을 만들지 못했습니다.');const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`umm-${activeName}.md`;anchor.click();URL.revokeObjectURL(url)};
  const canvasImage=async()=>{const target=document.querySelector('.react-flow') as HTMLElement|null;if(!target)throw new Error('Canvas를 찾을 수 없습니다.');return toPng(target,{backgroundColor:'#f8f5ee',pixelRatio:2,cacheBust:true})};
  const downloadImage=async()=>{if(!await ensureExport('image'))return;const data=await canvasImage();const anchor=document.createElement('a');anchor.href=data;anchor.download=`umm-${activeName}.png`;anchor.click()};
  const printPDF=async()=>{const printWindow=window.open('','_blank');if(!printWindow){window.alert('PDF를 만들려면 팝업을 허용해 주세요.');return};printWindow.opener=null;if(!await ensureExport('pdf')){printWindow.close();return};const data=await canvasImage();const safeName=activeName.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));printWindow.document.write(`<html><head><title>umm - ${safeName}</title><style>@page{size:landscape;margin:0}html,body{margin:0;width:100%;height:100%;display:grid;place-items:center}img{max-width:100%;max-height:100%;object-fit:contain}</style></head><body><img src="${data}" onload="window.print();window.close()"></body></html>`);printWindow.document.close()};
  const dismissDream = async () => { if (!morningDream) return; sessionStorage.setItem(`dream:${morningDream.dreamId}`, 'seen'); await api(`/dreams/${morningDream.dreamId}/feedback`, json('POST', { action: 'exposed' })).catch(() => undefined); setMorningDream(undefined); };
  const activeName = spaces.find(s => s.id === activeSpace)?.name || 'My Space';

  return <div className="canvas-page">
    {loading && <div className="canvas-loading" role="status" aria-label="생각 불러오는 중"><Loader color="grape" /></div>}
    <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeDragStart={onDragStart} onNodeDragStop={onDragStop} onPaneClick={(event) => { if (event.detail === 2) onPaneDoubleClick(event); }} fitView fitViewOptions={{ padding: .3 }} minZoom={.15} maxZoom={2.2} deleteKeyCode={null} selectionOnDrag panOnScroll>
      <Background variant={BackgroundVariant.Dots} color="transparent" /><Controls position="bottom-left" showInteractive={false} /><MiniMap position="bottom-right" pannable zoomable nodeColor={(node) => palette[(node.data as PostItData | undefined)?.note?.color || 'yellow'] || '#ddd'} maskColor="rgba(245,242,234,.7)" />
    </ReactFlow>
    <Paper className="canvas-toolbar" radius="xl" p={7}><Group gap={6} wrap="nowrap">
      <Menu shadow="md" width={300} position="bottom-start"><Menu.Target><Button className="space-switcher" variant="light" color="yellow.8" size="compact-sm" rightSection={<IconChevronDown size={14}/>} style={{textTransform:'none'}}>{activeName}</Button></Menu.Target><Menu.Dropdown>
        <Menu.Label>공간 {spaces.length}개</Menu.Label><div className="space-menu-search"><TextInput value={spaceQuery} onChange={event=>setSpaceQuery(event.currentTarget.value)} onKeyDown={event=>event.stopPropagation()} leftSection={<IconSearch size={15}/>} placeholder="공간 검색" size="xs"/></div>
        <ScrollArea.Autosize mah={260} type="auto">{visibleSpaces.map(space=><Menu.Item key={space.id} leftSection={<span className="space-dot" style={{background:space.color}}/>} rightSection={space.id===activeSpace?<IconCheck size={15}/>:undefined} onClick={()=>openSpace(space.id)}>{space.name}</Menu.Item>)}{visibleSpaces.length===0&&<Text size="xs" c="dimmed" ta="center" py="md">일치하는 공간이 없습니다.</Text>}</ScrollArea.Autosize>
        <Menu.Divider/><Menu.Item leftSection={<IconSettings size={16}/>} onClick={()=>{setSpaceError('');setSpaceManagerOpen(true)}}>공간 관리</Menu.Item><Menu.Item leftSection={<IconPlus size={16}/>} onClick={()=>{setSpaceError('');setSpaceManagerOpen(true)}}>새 공간 만들기</Menu.Item>
      </Menu.Dropdown></Menu>
      <TextInput id="thought-search" className="thought-search" aria-label="생각 검색" value={query} onChange={(e) => {setQuery(e.currentTarget.value);setSearchIndex(-1)}} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();focusSearchResult(event.shiftKey?-1:1)}if(event.key==='Escape'){event.preventDefault();setQuery('');setSearchIndex(-1)}}} leftSection={<IconSearch size={17}/>} rightSection={query?<Group gap={3} wrap="nowrap"><Badge size="xs" variant="light" color={searchMatches.length?'grape':'red'}>{searchMatches.length}</Badge><ActionIcon size="sm" variant="subtle" onClick={() => {setQuery('');setSearchIndex(-1)}} aria-label="검색어 지우기"><IconX size={14}/></ActionIcon></Group>:null} rightSectionWidth={query?66:undefined} placeholder="생각 검색  /" variant="filled" />
      <Group className="canvas-toolbar-actions" gap={2} wrap="nowrap"><Tooltip label="공간 공유"><ActionIcon className="canvas-action" variant="subtle" color="dark" onClick={()=>void openShare()} aria-label="공간 공유"><IconShare size={19}/></ActionIcon></Tooltip><Menu shadow="md"><Menu.Target><Tooltip label="내보내기"><ActionIcon className="canvas-action" variant="subtle" color="dark" aria-label="내보내기"><IconDownload size={19}/></ActionIcon></Tooltip></Menu.Target><Menu.Dropdown><Menu.Item leftSection={<IconMarkdown size={16}/>} onClick={()=>void downloadMarkdown()}>Markdown</Menu.Item><Menu.Item leftSection={<IconPhoto size={16}/>} onClick={()=>void downloadImage()}>Image (PNG)</Menu.Item><Menu.Item leftSection={<IconFileTypePdf size={16}/>} onClick={()=>void printPDF()}>PDF 인쇄</Menu.Item></Menu.Dropdown></Menu><Menu shadow="md"><Menu.Target><Tooltip label="선택한 생각 발전시키기"><ActionIcon className="canvas-action" loading={aiBusy} variant="subtle" color="grape" aria-label="AI 생각 도구"><IconBrain size={20}/></ActionIcon></Tooltip></Menu.Target><Menu.Dropdown><Menu.Label>AI는 조용히 도와줍니다</Menu.Label>{aiTools.map(([mode,label])=><Menu.Item key={mode} onClick={()=>void assist(mode)}>{label}</Menu.Item>)}</Menu.Dropdown></Menu><Tooltip label="관련 생각 군집 모으기"><ActionIcon className="canvas-action" variant="subtle" color="blue" onClick={()=>void clusterThoughts()} aria-label="생각 군집"><IconLayoutGrid size={20}/></ActionIcon></Tooltip><Tooltip label="직접 연결한 생각 모으기"><ActionIcon className="canvas-action" variant="subtle" color="grape" onClick={()=>gravity()} aria-label="Thought Gravity"><IconFocusCentered size={20}/></ActionIcon></Tooltip></Group>
      <Menu shadow="md" position="bottom-end"><Menu.Target><ActionIcon className="canvas-mobile-tools" variant="subtle" color="dark" aria-label="캔버스 도구"><IconDots size={21}/></ActionIcon></Menu.Target><Menu.Dropdown><Menu.Item leftSection={<IconShare size={17}/>} onClick={()=>void openShare()}>공간 공유</Menu.Item><Menu.Sub><Menu.Sub.Target><Menu.Sub.Item leftSection={<IconDownload size={17}/>}>내보내기</Menu.Sub.Item></Menu.Sub.Target><Menu.Sub.Dropdown><Menu.Item leftSection={<IconMarkdown size={16}/>} onClick={()=>void downloadMarkdown()}>Markdown</Menu.Item><Menu.Item leftSection={<IconPhoto size={16}/>} onClick={()=>void downloadImage()}>Image (PNG)</Menu.Item><Menu.Item leftSection={<IconFileTypePdf size={16}/>} onClick={()=>void printPDF()}>PDF 인쇄</Menu.Item></Menu.Sub.Dropdown></Menu.Sub><Menu.Sub><Menu.Sub.Target><Menu.Sub.Item leftSection={<IconBrain size={17}/>}>AI 생각 도구</Menu.Sub.Item></Menu.Sub.Target><Menu.Sub.Dropdown>{aiTools.map(([mode,label])=><Menu.Item key={mode} onClick={()=>void assist(mode)}>{label}</Menu.Item>)}</Menu.Sub.Dropdown></Menu.Sub><Menu.Item leftSection={<IconLayoutGrid size={17}/>} onClick={()=>void clusterThoughts()}>생각 군집 모으기</Menu.Item><Menu.Item leftSection={<IconFocusCentered size={17}/>} onClick={()=>gravity()}>연결한 생각 모으기</Menu.Item></Menu.Dropdown></Menu>
    </Group></Paper>
    {!loading && notes.length === 0 && <div className="onboarding-hint"><div><IconSparkles size={30} stroke={1.4}/><Text fz="lg" fw={650} mt="sm">여기 아무 곳이나 더블클릭 해보세요.</Text><Text c="dimmed" mt={4}>또는 아래에 생각을 바로 적어보세요.</Text></div></div>}
    {!loading&&searchTerms.length>0&&<Paper className="search-summary glass" radius="xl" px="md" py={7} role="status" aria-live="polite"><Text size="sm" fw={650}>{searchMatches.length===0?'일치하는 생각이 없습니다.':`${searchMatches.length}개의 생각을 찾았습니다.`}</Text>{searchMatches.length>0&&<Text size="xs" c="dimmed">Enter로 결과 이동{searchIndex>=0?` · ${searchIndex+1}/${searchMatches.length}`:''}</Text>}</Paper>}
    {!loading&&notes.length>0&&searchTerms.length>0&&searchMatches.length===0&&<div className="onboarding-hint"><div><IconSearch size={30} stroke={1.4}/><Text fz="lg" fw={650} mt="sm">검색 결과가 없습니다.</Text><Text c="dimmed" mt={4}>다른 단어를 입력하거나 Esc로 검색을 지워보세요.</Text></div></div>}
    <Paper className="quick-capture" radius="xl" p={7}><TextInput id="quick-thought" aria-label="새 생각" value={capture} onChange={(e) => setCapture(e.currentTarget.value)} onKeyDown={captureKey} placeholder="생각을 입력하고 Enter로 붙이세요" variant="unstyled" px="sm" rightSection={<ActionIcon variant="filled" color="dark" radius="xl" disabled={!capture.trim()} onClick={() => { const center=flow.screenToFlowPosition({x:window.innerWidth/2,y:window.innerHeight/2});void createAt(capture,center.x-120,center.y-80); }} aria-label="생각 붙이기"><IconArrowRight size={18}/></ActionIcon>} /></Paper>
    {morningDream && <div className="morning-overlay"><Paper radius="xl" p={{base:'xl',sm:40}} maw={520} mx="md" className="glass" ta="center"><IconMoonStars size={34} color="#76628f"/><Text size="sm" fw={700} c="grape.7" tt="uppercase" mt="sm">Dream</Text><Text fz={24} fw={660} mt="md">어젯밤, 당신의 생각이 꿈을 꾸었습니다.</Text><Text fz="lg" lh={1.65} mt="lg">{morningDream.content}</Text><Group justify="center" mt="xl"><Button variant="light" color="grape" onClick={dismissDream}>생각 곁에서 보기</Button></Group></Paper></div>}
    {related&&<Paper className="related-panel glass" radius="lg" p="md"><Group justify="space-between"><Text fw={700}>Related {related.items.length}</Text><ActionIcon variant="subtle" onClick={()=>setRelated(undefined)}><IconX size={16}/></ActionIcon></Group><Stack gap="xs" mt="sm">{related.items.map(item=><button key={item.note.id} className="related-row" onClick={()=>flow.fitView({nodes:[{id:item.note.id}],duration:500,padding:.8})}><Text lineClamp={2} ta="left">{item.note.content}</Text><Text size="xs" c="dimmed" ta="left">{item.reason} · {Math.round(item.score*100)}%</Text></button>)}</Stack></Paper>}
    <Modal opened={!!aiResult} onClose={()=>setAIResult(undefined)} title="생각이 한 단계 자랐습니다" centered size="lg"><Stack><Paper p="lg" radius="lg" bg="grape.0"><Text lh={1.75} style={{whiteSpace:'pre-wrap'}}>{aiResult?.content}</Text></Paper><Group justify="flex-end"><Button variant="light" onClick={()=>setAIResult(undefined)}>그대로 두기</Button><Button onClick={()=>{const center=flow.screenToFlowPosition({x:window.innerWidth/2,y:window.innerHeight/2});void createAt(aiResult?.content||'',center.x-120,center.y-80);setAIResult(undefined)}}>새 생각으로 붙이기</Button></Group></Stack></Modal>
    <Modal opened={spaceManagerOpen} onClose={()=>{setSpaceManagerOpen(false);setSpaceQuery('');setSpaceError('')}} title="공간 관리" centered size="lg"><Stack>
      <Text c="dimmed" size="sm">공간을 검색하고 이동하거나, 소유한 공간의 이름을 바꾸고 삭제할 수 있습니다.</Text>
      {spaceError&&<Alert color="red" withCloseButton onClose={()=>setSpaceError('')}>{spaceError}</Alert>}
      <Group align="flex-end"><TextInput label="새 공간" placeholder="공간 이름" value={newSpaceName} maxLength={200} onChange={event=>setNewSpaceName(event.currentTarget.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void addSpace()}}} style={{flex:1}}/><Button leftSection={<IconPlus size={16}/>} loading={spaceBusy==='new'} disabled={!newSpaceName.trim()} onClick={()=>void addSpace()}>만들기</Button></Group>
      <Divider/><TextInput value={spaceQuery} onChange={event=>setSpaceQuery(event.currentTarget.value)} leftSection={<IconSearch size={16}/>} placeholder={`공간 ${spaces.length}개 중 검색`}/>
      <ScrollArea.Autosize mah={420} type="auto"><Stack gap="sm">{visibleSpaces.map(space=>{const owned=space.ownerId===user?.id;const changed=(spaceDrafts[space.id]||'').trim()!==space.name;return <Paper key={space.id} className="space-manager-row" p="sm" radius="md" withBorder><Group wrap="nowrap" align="flex-end"><TextInput label={owned?'내 공간':'공유 공간'} value={spaceDrafts[space.id]??space.name} disabled={!owned} maxLength={200} onChange={event=>setSpaceDrafts(all=>({...all,[space.id]:event.currentTarget.value}))} style={{flex:1}}/><Group gap={5} wrap="nowrap"><Tooltip label="이동"><ActionIcon variant={space.id===activeSpace?'filled':'light'} color="grape" aria-label={`${space.name}으로 이동`} onClick={()=>{openSpace(space.id);setSpaceManagerOpen(false)}}><IconArrowRight size={17}/></ActionIcon></Tooltip>{owned&&<Tooltip label="이름 저장"><ActionIcon variant="light" color="blue" loading={spaceBusy===space.id} disabled={!changed||!(spaceDrafts[space.id]||'').trim()} aria-label={`${space.name} 이름 저장`} onClick={()=>void renameSpace(space)}><IconEdit size={16}/></ActionIcon></Tooltip>}{owned&&<Tooltip label="공간 삭제"><ActionIcon variant="light" color="red" aria-label={`${space.name} 삭제`} onClick={()=>{setDeleteCandidate(space);setDeleteConfirmation('')}}><IconTrash size={16}/></ActionIcon></Tooltip>}</Group></Group>{space.id===activeSpace&&<Badge mt="xs" size="xs" variant="light">현재 공간</Badge>}</Paper>})}{visibleSpaces.length===0&&<Text c="dimmed" ta="center" py="xl">일치하는 공간이 없습니다.</Text>}</Stack></ScrollArea.Autosize>
    </Stack></Modal>
    <Modal opened={!!deleteCandidate} onClose={()=>{if(!spaceBusy.startsWith('delete:')){setDeleteCandidate(undefined);setDeleteConfirmation('')}}} title="공간을 삭제할까요?" centered size="md" closeOnClickOutside={!spaceBusy.startsWith('delete:')}><Stack><Alert color="red" icon={<IconTrash size={18}/>}>공간 안의 메모, 연결, Dream 기록과 공유 정보가 모두 삭제됩니다. 이 작업은 되돌릴 수 없습니다.</Alert>{spaceError&&<Alert color="red">{spaceError}</Alert>}<Text size="sm">확인을 위해 <b>{deleteCandidate?.name}</b>을 입력하세요.</Text><TextInput autoFocus value={deleteConfirmation} onChange={event=>setDeleteConfirmation(event.currentTarget.value)} placeholder={deleteCandidate?.name}/><Group justify="flex-end"><Button variant="default" onClick={()=>{setDeleteCandidate(undefined);setDeleteConfirmation('');setSpaceError('')}}>취소</Button><Button color="red" loading={spaceBusy===`delete:${deleteCandidate?.id}`} disabled={!deleteCandidate||deleteConfirmation!==deleteCandidate.name} onClick={()=>void deleteSpace()}>영구 삭제</Button></Group></Stack></Modal>
    <Modal opened={shareOpen} onClose={()=>setShareOpen(false)} title="이 공간 함께 쓰기" centered size="lg"><Stack>{shareMessage&&<Paper p="sm" bg="grape.0"><Text size="sm">{shareMessage}</Text></Paper>}{canManage&&<Group align="flex-end"><TextInput label="사용자 아이디" placeholder="username" value={shareUser} onChange={e=>setShareUser(e.currentTarget.value)} style={{flex:1}}/><Select label="권한" value={sharePermission} onChange={v=>v&&setSharePermission(v)} data={[{value:'view',label:'보기'},{value:'edit',label:'편집'},{value:'manage',label:'관리'}]} w={120}/><Button disabled={!shareUser.trim()} onClick={()=>void share()}>초대</Button></Group>}<Stack gap="xs">{members.map(member=><Paper key={member.id} p="sm" bg="gray.0"><Group justify="space-between"><div><Text fw={600}>{member.displayName}</Text><Text size="xs" c="dimmed">{member.username} · {member.permission}</Text></div>{canManage&&member.permission!=='owner'&&<ActionIcon color="red" variant="subtle" onClick={()=>void removeMember(member.id)}><IconTrash size={16}/></ActionIcon>}</Group></Paper>)}</Stack></Stack></Modal>
  </div>;
}

export default function CanvasPage(){return <ReactFlowProvider><CanvasInner/></ReactFlowProvider>;}
