import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from 'react';
import { ActionIcon, Badge, Button, Group, Loader, Menu, Modal, Paper, Select, Stack, Text, TextInput, Tooltip } from '@mantine/core';
import { IconArrowRight, IconBrain, IconChevronDown, IconDots, IconDownload, IconFileTypePdf, IconFocusCentered, IconLayoutGrid, IconMarkdown, IconMoonStars, IconPhoto, IconPlus, IconSearch, IconShare, IconSparkles, IconTrash, IconX } from '@tabler/icons-react';
import { ReactFlow, addEdge, Background, BackgroundVariant, Controls, MiniMap, ReactFlowProvider, useEdgesState, useNodesState, useReactFlow, type Connection, type Edge, type Node, type OnNodeDrag } from '@xyflow/react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, json, type Space, type ThoughtEdge, type ThoughtNote } from '../api';
import PostItNode, { type PostItData } from '../components/PostItNode';
import { useAuth } from '../auth-context';
import { toPng } from 'html-to-image';

const nodeTypes = { postit: PostItNode };
const palette: Record<string, string> = { yellow: '#fff0a8', blue: '#dbeeff', purple: '#e9def8', lavender: '#e8e2f1', green: '#d9f0dc', red: '#f8deda', gray: '#e9e7e1' };
const aiTools = [['summarize','요약'],['questions','질문 만들기'],['expand','확장'],['challenge','반대 관점'],['actions','실행 항목']];

interface DreamHistory { dreamId: string; status: string; content: string; spaceId: string; qualityScore: number; }
interface HistoryAction { id: string; before: { x: number; y: number }; after: { x: number; y: number }; }
interface RelatedThought {note:ThoughtNote;score:number;reason:string}
interface Cluster {id:string;label:string;noteIds:string[];cohesion:number}
interface SpaceMember {id:string;username:string;displayName:string;email:string;permission:string}

function CanvasInner() {
  const params = useParams(); const navigate = useNavigate(); const flow = useReactFlow();
  const {user}=useAuth();
  const [spaces, setSpaces] = useState<Space[]>([]); const [activeSpace, setActiveSpace] = useState('');
  const [notes, setNotes] = useState<ThoughtNote[]>([]); const [rawEdges, setRawEdges] = useState<ThoughtEdge[]>([]);
  const [nodes, setNodes, onNodesChange] = useNodesState<Node<PostItData>>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);
  const [query, setQuery] = useState(''); const [capture, setCapture] = useState(''); const [loading, setLoading] = useState(true);
  const [morningDream, setMorningDream] = useState<DreamHistory>();
  const [related,setRelated]=useState<{source:string;items:RelatedThought[]}>();const [aiResult,setAIResult]=useState<{mode:string;content:string}>();const [aiBusy,setAIBusy]=useState(false);
  const [shareOpen,setShareOpen]=useState(false);const [members,setMembers]=useState<SpaceMember[]>([]);const [canManage,setCanManage]=useState(false);const [shareUser,setShareUser]=useState('');const [sharePermission,setSharePermission]=useState('edit');const [shareMessage,setShareMessage]=useState('');
  const notesRef = useRef<Record<string, ThoughtNote>>({}); const queues = useRef<Record<string, Promise<void>>>({});
  const dragStart = useRef<Record<string, {x:number;y:number}>>({}); const undo = useRef<HistoryAction[]>([]); const redo = useRef<HistoryAction[]>([]);

  const syncNotes = (next: ThoughtNote[]) => { setNotes(next); notesRef.current = Object.fromEntries(next.map((n) => [n.id, n])); };
  useEffect(() => { api<{spaces: Space[]}>('/spaces').then(({spaces}) => { setSpaces(spaces); const desired = params.spaceId && spaces.some(s => s.id === params.spaceId) ? params.spaceId : spaces[0]?.id; if (desired) { setActiveSpace(desired); if (!params.spaceId) navigate(`/space/${desired}`, { replace: true }); } }).catch(console.error); }, []);
  useEffect(() => { if (params.spaceId && params.spaceId !== activeSpace) setActiveSpace(params.spaceId); }, [params.spaceId]);
  const loadCanvas=useCallback(async(silent=false)=>{if(!activeSpace)return;if(!silent)setLoading(true);try{const v=await api<{notes:ThoughtNote[];edges:ThoughtEdge[]}>(`/spaces/${activeSpace}/notes`);syncNotes(v.notes);setRawEdges(v.edges)}finally{if(!silent)setLoading(false)}},[activeSpace]);
  useEffect(() => { if (!activeSpace) return; void loadCanvas(); api<{dreams: DreamHistory[]}>('/dreams').then(({dreams}) => { const fresh = dreams.find(d => d.spaceId === activeSpace && d.status === 'created'); if (fresh && !sessionStorage.getItem(`dream:${fresh.dreamId}`)) setMorningDream(fresh); }).catch(() => undefined); }, [activeSpace,loadCanvas]);
  useEffect(()=>{if(!activeSpace)return;const stream=new EventSource(`/api/v1/spaces/${activeSpace}/events`);stream.addEventListener('space-change',(event)=>{try{const data=JSON.parse((event as MessageEvent).data);if(data.actorId!==user?.id)void loadCanvas(true)}catch{void loadCanvas(true)}});return()=>stream.close()},[activeSpace,user?.id,loadCanvas]);

  const persist = useCallback((id: string, patch: Partial<ThoughtNote>) => {
    const current = notesRef.current[id]; if (!current) return;
    notesRef.current[id] = { ...current, ...patch }; setNotes((all) => all.map((n) => n.id === id ? { ...n, ...patch } : n));
    const previous = queues.current[id] || Promise.resolve();
    queues.current[id] = previous.catch(() => undefined).then(async () => {
      const base = notesRef.current[id]; if (!base) return;
      const updated = await api<ThoughtNote>(`/notes/${id}`, json('PUT', base));
      notesRef.current[id] = { ...notesRef.current[id], version: updated.version, updatedAt: updated.updatedAt };
      setNotes((all) => all.map((n) => n.id === id ? { ...n, version: updated.version, updatedAt: updated.updatedAt } : n));
    }).catch((error) => console.error('autosave failed', error));
  }, []);

  const remove = useCallback(async (id: string) => { await api(`/notes/${id}`, { method: 'DELETE' }); delete notesRef.current[id]; setNotes((all) => all.filter((n) => n.id !== id)); setRawEdges((all) => all.filter((e) => e.source !== id && e.target !== id)); }, []);
  const restore=useCallback(async(id:string)=>{const result=await api<{history:Array<{version:number;createdAt:string}>}>(`/notes/${id}/history`);const latest=result.history[0];if(!latest){window.alert('복원할 이전 버전이 없습니다.');return};if(!window.confirm(`${new Date(latest.createdAt).toLocaleString('ko-KR')}의 버전으로 되돌릴까요? 현재 상태도 기록에 남습니다.`))return;const restored=await api<ThoughtNote>(`/notes/${id}/restore/${latest.version}`,{method:'POST'});notesRef.current[id]=restored;setNotes(all=>all.map(n=>n.id===id?restored:n))},[]);

  const gravity = useCallback((selectedID?:string) => { const selected = selectedID ? flow.getNode(selectedID) : flow.getNodes().find(n => n.selected); if (!selected) return; const related = new Set<string>(); rawEdges.forEach(e => { if (e.source === selected.id) related.add(e.target); if (e.target === selected.id) related.add(e.source); }); [...related].forEach((id, index) => { const angle = index / Math.max(1, related.size) * Math.PI * 2; const patch = { x: selected.position.x + Math.cos(angle) * 330, y: selected.position.y + Math.sin(angle) * 230 }; persist(id, patch); }); },[flow,rawEdges,persist]);
  const discoverRelated=useCallback(async(id:string)=>{const result=await api<{related:RelatedThought[]}>(`/notes/${id}/related?limit=8`);setRelated({source:id,items:result.related});const source=flow.getNode(id);if(source){result.related.forEach((item,index)=>{const angle=index/Math.max(1,result.related.length)*Math.PI*2;persist(item.note.id,{x:source.position.x+Math.cos(angle)*360,y:source.position.y+Math.sin(angle)*245})})}},[flow,persist]);

  useEffect(() => {
    const q = query.trim().toLocaleLowerCase();
    setNodes(notes.map((note) => ({ id: note.id, type: 'postit', position: { x: note.x, y: note.y }, style: { width: note.width, height: note.height }, data: { note, dimmed: !!q && !`${note.title} ${note.content}`.toLocaleLowerCase().includes(q), relatedCount: note.relatedCount, onGather: discoverRelated, onPatch: persist, onDelete: remove,onRestore:restore } })));
  }, [notes, query, persist, remove, restore,discoverRelated]);
  useEffect(() => setEdges(rawEdges.map((e) => ({ id: e.id, source: e.source, target: e.target, type: 'smoothstep', animated: e.relation === 'dreamed', label: e.relation === 'related' ? undefined : e.relation }))), [rawEdges]);

  const createAt = useCallback(async (content: string, x: number, y: number) => {
    if (!activeSpace) return; const trimmed = content.trim();
    const created = await api<ThoughtNote>(`/spaces/${activeSpace}/notes`, json('POST', { spaceId: activeSpace, content: trimmed, title: '', color: 'yellow', kind: 'thought', source: 'user', x, y, width: 240, height: 160, rotation: Math.round((Math.random() - .5) * 2), version: 0, authorId: '', id: '', createdAt: '', updatedAt: '' }));
    syncNotes([...Object.values(notesRef.current), created]); setCapture('');
  }, [activeSpace]);

  const onPaneDoubleClick = useCallback((event: React.MouseEvent) => { const point = flow.screenToFlowPosition({ x: event.clientX, y: event.clientY }); void createAt('', point.x, point.y); }, [flow, createAt]);
  const connect = useCallback(async (connection: Connection) => { if (!connection.source || !connection.target) return; const created = await api<ThoughtEdge>(`/spaces/${activeSpace}/edges`, json('POST', { id: '', spaceId: activeSpace, source: connection.source, target: connection.target, relation: 'related' })); setRawEdges((all) => [...all, created]); setEdges((all) => addEdge({ ...connection, id: created.id, type: 'smoothstep' }, all)); }, [activeSpace]);
  const onDragStart: OnNodeDrag<Node<PostItData>> = (_, node) => { dragStart.current[node.id] = { ...node.position }; };
  const onDragStop: OnNodeDrag<Node<PostItData>> = (_, node) => { const before = dragStart.current[node.id]; const after = { ...node.position }; if (before && (before.x !== after.x || before.y !== after.y)) { undo.current.push({ id: node.id, before, after }); redo.current = []; } persist(node.id, { x: after.x, y: after.y }); };

  useEffect(() => {
    const onKey = (event: globalThis.KeyboardEvent) => {
      const target = event.target as HTMLElement; const editing = ['INPUT','TEXTAREA'].includes(target.tagName) || target.isContentEditable;
      if (!editing && (event.key.toLowerCase() === 'n' || event.key === '/')) { event.preventDefault(); document.getElementById('quick-thought')?.focus(); }
      if (!editing && (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); const action = event.shiftKey ? redo.current.pop() : undo.current.pop(); if (!action) return; const position = event.shiftKey ? action.after : action.before; persist(action.id, position); setNodes((all) => all.map(n => n.id === action.id ? { ...n, position } : n)); (event.shiftKey ? undo.current : redo.current).push(action); }
    }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  }, [persist]);

  const captureKey = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === 'Enter' && capture.trim()) { const center = flow.screenToFlowPosition({ x: window.innerWidth / 2, y: window.innerHeight / 2 }); void createAt(capture, center.x - 120, center.y - 80); } };
  const addSpace=async()=>{const name=window.prompt('새 공간 이름');if(!name?.trim())return;const created=await api<Space>('/spaces',json('POST',{name}));setSpaces(all=>[...all,created]);navigate(`/space/${created.id}`)};
  const clusterThoughts=async()=>{const {clusters}=await api<{clusters:Cluster[]}>(`/spaces/${activeSpace}/clusters`);clusters.forEach((cluster,clusterIndex)=>cluster.noteIds.forEach((id,noteIndex)=>persist(id,{x:clusterIndex*620+(noteIndex%2)*270,y:Math.floor(noteIndex/2)*205})));if(clusters.length===0)window.alert('아직 뚜렷한 생각 군집이 없습니다. 조금 더 생각을 붙여보세요.')};
  const assist=async(mode:string)=>{const selected=flow.getNodes().filter(n=>n.selected).map(n=>n.id);if(selected.length===0){window.alert('AI와 발전시킬 생각을 하나 이상 선택하세요.');return};setAIBusy(true);try{setAIResult(await api('/ai/assist',json('POST',{noteIds:selected,mode})))}finally{setAIBusy(false)}};
  const loadMembers=async()=>{const v=await api<{members:SpaceMember[];canManage:boolean}>(`/spaces/${activeSpace}/members`);setMembers(v.members);setCanManage(v.canManage)};const openShare=async()=>{await loadMembers();setShareOpen(true)};const share=async()=>{const v=await api<{required:boolean;status:string}>(`/spaces/${activeSpace}/members`,json('POST',{username:shareUser,permission:sharePermission}));setShareMessage(v.required?'팀장 검토를 요청했습니다. 승인되면 자동으로 공유됩니다.':'공간을 공유했습니다.');setShareUser('');await loadMembers()};const removeMember=async(id:string)=>{await api(`/spaces/${activeSpace}/members/${id}`,{method:'DELETE'});await loadMembers()};
  const ensureExport=async(format:string)=>{const response=await fetch(`/api/v1/spaces/${activeSpace}/export/authorize?format=${format}`,{credentials:'same-origin'});if(response.ok)return true;const payload=await response.json().catch(()=>({}));if(response.status===409&&payload.code==='approval_required'){const request=await api<{required:boolean;status:string}>('/approvals',json('POST',{resourceType:'space',resourceId:activeSpace,action:'export',comment:`${format} 내보내기 요청`}));window.alert(request.required?'팀장 검토를 요청했습니다. 승인 후 24시간 동안 내보낼 수 있습니다.':'내보내기가 허용되었습니다.');return !request.required}throw new Error(payload.error||'내보내기 권한을 확인하지 못했습니다.')};
  const downloadMarkdown=async()=>{if(!await ensureExport('markdown'))return;const response=await fetch(`/api/v1/spaces/${activeSpace}/export/markdown`,{credentials:'same-origin'});if(!response.ok)throw new Error('Markdown을 만들지 못했습니다.');const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`umm-${activeName}.md`;anchor.click();URL.revokeObjectURL(url)};
  const canvasImage=async()=>{const target=document.querySelector('.react-flow') as HTMLElement|null;if(!target)throw new Error('Canvas를 찾을 수 없습니다.');return toPng(target,{backgroundColor:'#f8f5ee',pixelRatio:2,cacheBust:true})};
  const downloadImage=async()=>{if(!await ensureExport('image'))return;const data=await canvasImage();const anchor=document.createElement('a');anchor.href=data;anchor.download=`umm-${activeName}.png`;anchor.click()};
  const printPDF=async()=>{const printWindow=window.open('','_blank');if(!printWindow){window.alert('PDF를 만들려면 팝업을 허용해 주세요.');return};printWindow.opener=null;if(!await ensureExport('pdf')){printWindow.close();return};const data=await canvasImage();const safeName=activeName.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));printWindow.document.write(`<html><head><title>umm - ${safeName}</title><style>@page{size:landscape;margin:0}html,body{margin:0;width:100%;height:100%;display:grid;place-items:center}img{max-width:100%;max-height:100%;object-fit:contain}</style></head><body><img src="${data}" onload="window.print();window.close()"></body></html>`);printWindow.document.close()};
  const dismissDream = async () => { if (!morningDream) return; sessionStorage.setItem(`dream:${morningDream.dreamId}`, 'seen'); await api(`/dreams/${morningDream.dreamId}/feedback`, json('POST', { action: 'exposed' })).catch(() => undefined); setMorningDream(undefined); };
  const activeName = spaces.find(s => s.id === activeSpace)?.name || 'My Space';

  return <div className="canvas-page">
    {loading && <div className="canvas-loading" role="status" aria-label="생각 불러오는 중"><Loader color="grape" /></div>}
    <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeDragStart={onDragStart} onNodeDragStop={onDragStop} onPaneClick={(event) => { if (event.detail === 2) onPaneDoubleClick(event); }} fitView fitViewOptions={{ padding: .3 }} minZoom={.15} maxZoom={2.2} deleteKeyCode={null} selectionOnDrag panOnScroll>
      <Background variant={BackgroundVariant.Dots} color="transparent" /><Controls position="bottom-left" showInteractive={false} /><MiniMap position="bottom-right" pannable zoomable nodeColor={(node) => palette[(node.data as PostItData | undefined)?.note?.color || 'yellow'] || '#ddd'} maskColor="rgba(245,242,234,.7)" />
    </ReactFlow>
    <Paper className="canvas-toolbar" radius="xl" p={7}><Group gap={6} wrap="nowrap"><Menu shadow="md"><Menu.Target><Button className="space-switcher" variant="light" color="yellow.8" size="compact-sm" rightSection={<IconChevronDown size={14}/>} style={{textTransform:'none'}}>{activeName}</Button></Menu.Target><Menu.Dropdown><Menu.Label>공간</Menu.Label>{spaces.map(space=><Menu.Item key={space.id} onClick={()=>navigate(`/space/${space.id}`)}>{space.name}</Menu.Item>)}<Menu.Divider/><Menu.Item leftSection={<IconPlus size={15}/>} onClick={()=>void addSpace()}>새 공간</Menu.Item></Menu.Dropdown></Menu><TextInput className="thought-search" aria-label="생각 검색" value={query} onChange={(e) => setQuery(e.currentTarget.value)} leftSection={<IconSearch size={17}/>} rightSection={query?<ActionIcon variant="subtle" onClick={() => setQuery('')} aria-label="검색어 지우기"><IconX size={15}/></ActionIcon>:null} placeholder="생각 검색" variant="filled" />
      <Group className="canvas-toolbar-actions" gap={2} wrap="nowrap"><Tooltip label="공간 공유"><ActionIcon className="canvas-action" variant="subtle" color="dark" onClick={()=>void openShare()} aria-label="공간 공유"><IconShare size={19}/></ActionIcon></Tooltip><Menu shadow="md"><Menu.Target><Tooltip label="내보내기"><ActionIcon className="canvas-action" variant="subtle" color="dark" aria-label="내보내기"><IconDownload size={19}/></ActionIcon></Tooltip></Menu.Target><Menu.Dropdown><Menu.Item leftSection={<IconMarkdown size={16}/>} onClick={()=>void downloadMarkdown()}>Markdown</Menu.Item><Menu.Item leftSection={<IconPhoto size={16}/>} onClick={()=>void downloadImage()}>Image (PNG)</Menu.Item><Menu.Item leftSection={<IconFileTypePdf size={16}/>} onClick={()=>void printPDF()}>PDF 인쇄</Menu.Item></Menu.Dropdown></Menu><Menu shadow="md"><Menu.Target><Tooltip label="선택한 생각 발전시키기"><ActionIcon className="canvas-action" loading={aiBusy} variant="subtle" color="grape" aria-label="AI 생각 도구"><IconBrain size={20}/></ActionIcon></Tooltip></Menu.Target><Menu.Dropdown><Menu.Label>AI는 조용히 도와줍니다</Menu.Label>{aiTools.map(([mode,label])=><Menu.Item key={mode} onClick={()=>void assist(mode)}>{label}</Menu.Item>)}</Menu.Dropdown></Menu><Tooltip label="관련 생각 군집 모으기"><ActionIcon className="canvas-action" variant="subtle" color="blue" onClick={()=>void clusterThoughts()} aria-label="생각 군집"><IconLayoutGrid size={20}/></ActionIcon></Tooltip><Tooltip label="직접 연결한 생각 모으기"><ActionIcon className="canvas-action" variant="subtle" color="grape" onClick={()=>gravity()} aria-label="Thought Gravity"><IconFocusCentered size={20}/></ActionIcon></Tooltip></Group>
      <Menu shadow="md" position="bottom-end"><Menu.Target><ActionIcon className="canvas-mobile-tools" variant="subtle" color="dark" aria-label="캔버스 도구"><IconDots size={21}/></ActionIcon></Menu.Target><Menu.Dropdown><Menu.Item leftSection={<IconShare size={17}/>} onClick={()=>void openShare()}>공간 공유</Menu.Item><Menu.Sub><Menu.Sub.Target><Menu.Sub.Item leftSection={<IconDownload size={17}/>}>내보내기</Menu.Sub.Item></Menu.Sub.Target><Menu.Sub.Dropdown><Menu.Item leftSection={<IconMarkdown size={16}/>} onClick={()=>void downloadMarkdown()}>Markdown</Menu.Item><Menu.Item leftSection={<IconPhoto size={16}/>} onClick={()=>void downloadImage()}>Image (PNG)</Menu.Item><Menu.Item leftSection={<IconFileTypePdf size={16}/>} onClick={()=>void printPDF()}>PDF 인쇄</Menu.Item></Menu.Sub.Dropdown></Menu.Sub><Menu.Sub><Menu.Sub.Target><Menu.Sub.Item leftSection={<IconBrain size={17}/>}>AI 생각 도구</Menu.Sub.Item></Menu.Sub.Target><Menu.Sub.Dropdown>{aiTools.map(([mode,label])=><Menu.Item key={mode} onClick={()=>void assist(mode)}>{label}</Menu.Item>)}</Menu.Sub.Dropdown></Menu.Sub><Menu.Item leftSection={<IconLayoutGrid size={17}/>} onClick={()=>void clusterThoughts()}>생각 군집 모으기</Menu.Item><Menu.Item leftSection={<IconFocusCentered size={17}/>} onClick={()=>gravity()}>연결한 생각 모으기</Menu.Item></Menu.Dropdown></Menu>
    </Group></Paper>
    {!loading && notes.length === 0 && <div className="onboarding-hint"><div><IconSparkles size={30} stroke={1.4}/><Text fz="lg" fw={650} mt="sm">여기 아무 곳이나 더블클릭 해보세요.</Text><Text c="dimmed" mt={4}>또는 아래에 생각을 바로 적어보세요.</Text></div></div>}
    <Paper className="quick-capture" radius="xl" p={7}><TextInput id="quick-thought" aria-label="새 생각" value={capture} onChange={(e) => setCapture(e.currentTarget.value)} onKeyDown={captureKey} placeholder="생각을 입력하고 Enter로 붙이세요" variant="unstyled" px="sm" rightSection={<ActionIcon variant="filled" color="dark" radius="xl" disabled={!capture.trim()} onClick={() => { const center=flow.screenToFlowPosition({x:window.innerWidth/2,y:window.innerHeight/2});void createAt(capture,center.x-120,center.y-80); }} aria-label="생각 붙이기"><IconArrowRight size={18}/></ActionIcon>} /></Paper>
    {morningDream && <div className="morning-overlay"><Paper radius="xl" p={{base:'xl',sm:40}} maw={520} mx="md" className="glass" ta="center"><IconMoonStars size={34} color="#76628f"/><Text size="sm" fw={700} c="grape.7" tt="uppercase" mt="sm">Dream</Text><Text fz={24} fw={660} mt="md">어젯밤, 당신의 생각이 꿈을 꾸었습니다.</Text><Text fz="lg" lh={1.65} mt="lg">{morningDream.content}</Text><Group justify="center" mt="xl"><Button variant="light" color="grape" onClick={dismissDream}>생각 곁에서 보기</Button></Group></Paper></div>}
    {related&&<Paper className="related-panel glass" radius="lg" p="md"><Group justify="space-between"><Text fw={700}>Related {related.items.length}</Text><ActionIcon variant="subtle" onClick={()=>setRelated(undefined)}><IconX size={16}/></ActionIcon></Group><Stack gap="xs" mt="sm">{related.items.map(item=><button key={item.note.id} className="related-row" onClick={()=>flow.fitView({nodes:[{id:item.note.id}],duration:500,padding:.8})}><Text lineClamp={2} ta="left">{item.note.content}</Text><Text size="xs" c="dimmed" ta="left">{item.reason} · {Math.round(item.score*100)}%</Text></button>)}</Stack></Paper>}
    <Modal opened={!!aiResult} onClose={()=>setAIResult(undefined)} title="생각이 한 단계 자랐습니다" centered size="lg"><Stack><Paper p="lg" radius="lg" bg="grape.0"><Text lh={1.75} style={{whiteSpace:'pre-wrap'}}>{aiResult?.content}</Text></Paper><Group justify="flex-end"><Button variant="light" onClick={()=>setAIResult(undefined)}>그대로 두기</Button><Button onClick={()=>{const center=flow.screenToFlowPosition({x:window.innerWidth/2,y:window.innerHeight/2});void createAt(aiResult?.content||'',center.x-120,center.y-80);setAIResult(undefined)}}>새 생각으로 붙이기</Button></Group></Stack></Modal>
    <Modal opened={shareOpen} onClose={()=>setShareOpen(false)} title="이 공간 함께 쓰기" centered size="lg"><Stack>{shareMessage&&<Paper p="sm" bg="grape.0"><Text size="sm">{shareMessage}</Text></Paper>}{canManage&&<Group align="flex-end"><TextInput label="사용자 아이디" placeholder="username" value={shareUser} onChange={e=>setShareUser(e.currentTarget.value)} style={{flex:1}}/><Select label="권한" value={sharePermission} onChange={v=>v&&setSharePermission(v)} data={[{value:'view',label:'보기'},{value:'edit',label:'편집'},{value:'manage',label:'관리'}]} w={120}/><Button disabled={!shareUser.trim()} onClick={()=>void share()}>초대</Button></Group>}<Stack gap="xs">{members.map(member=><Paper key={member.id} p="sm" bg="gray.0"><Group justify="space-between"><div><Text fw={600}>{member.displayName}</Text><Text size="xs" c="dimmed">{member.username} · {member.permission}</Text></div>{canManage&&member.permission!=='owner'&&<ActionIcon color="red" variant="subtle" onClick={()=>void removeMember(member.id)}><IconTrash size={16}/></ActionIcon>}</Group></Paper>)}</Stack></Stack></Modal>
  </div>;
}

export default function CanvasPage(){return <ReactFlowProvider><CanvasInner/></ReactFlowProvider>;}
